version: '3.3'
services:
  eureka-service:
    image: 'smahler/epb-eureka-service:latest'
    container_name: eureka-service
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - '8761:8761'
  test-service:
    image: 'smahler/epb-test-service:latest'
    container_name: test-service
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    links:
      - eureka-service
    ports:
      - '1001:1001'
  test-service2:
    image: 'smahler/epb-test-service2:latest'
    container_name: test-service2
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    links:
      - eureka-service
    ports:
      - '1002:1002'
  eureka-prometheus-bridge:
    build: .
    container_name: eureka-prometheus-bridge
    ports:
      - '1111:1111'
  prometheus:
    image: prom/prometheus:v2.1.0
    container_name: prometheus
    volumes:
      - prometheus-data
    ports:
      - '9090:9090'
    configs:
      - source: generated_config
        target: etc/prometheus/prometheus.yml
generated_config:
  file: generated-prometheus-configs/prometheus.yml
