version: '3.3'
services:
  eureka-service:
    image: 'smahler/epb-eureka-service:latest'
    container_name: eureka-service
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - '8761:8761'
    networks:
      - local
  test-service:
    image: 'smahler/epb-test-service:latest'
    container_name: test-service
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    links:
      - eureka-service
    ports:
      - '1001:1001'
    networks:
      - local
  test-service2:
    image: 'smahler/epb-test-service2:latest'
    container_name: test-service2
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    links:
      - eureka-service
    ports:
      - '1002:1002'
    networks:
      - local
  eureka-prometheus-bridge:
    build: .
    container_name: eureka-prometheus-bridge
    ports:
      - '1111:1111'
    networks:
      - local
  prometheus:
    build: dockerfile-prometheus/.
    container_name: prometheus
    restart: on-failure
    volumes:
      - prometheus-data
    ports:
      - '9090:9090'
    networks:
      - local
networks:
  local:
    driver: bridge